---

- name: Activate apache proxy
  community.general.apache2_module:
    state: present
    name: proxy
  notify:
    - Restart apache

- name: Activate apache proxy_wstunnel
  community.general.apache2_module:
    state: present
    name: proxy_wstunnel
  notify:
    - Restart apache

- name: Activate apache proxy_http
  community.general.apache2_module:
    state: present
    name: proxy_http
  notify:
    - Restart apache

- name: Activate apache ssl
  community.general.apache2_module:
    state: present
    name: ssl
  notify:
    - Restart apache

- name: Setup apache reverse proxy for collabora
  ansible.builtin.template:
    src: apache-collabora.conf
    dest: /etc/apache2/snippets/{{ collabora_fqdn }}/collabora.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart apache
