---

- name: Install collabora apt key
  ansible.builtin.get_url:
    url: https://collaboraoffice.com/downloads/gpg/collaboraonline-release-keyring.gpg
    dest: /usr/share/keyrings/
    mode: '0644'

- name: Add collabora apt repository (Ubuntu 22.04 pinned)
  ansible.builtin.apt_repository:
    filename: collabora
    repo: 'deb [signed-by=/usr/share/keyrings/collaboraonline-release-keyring.gpg] https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2204 ./'
    validate_certs: true
    update_cache: true
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('22.04', '==')

- name: Add collabora apt repository (Others, rolling)
  ansible.builtin.apt_repository:
    filename: collabora
    repo: 'deb [signed-by=/usr/share/keyrings/collaboraonline-release-keyring.gpg] https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-deb ./'
    validate_certs: true
    update_cache: true
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is not version('22.04', '==')

- name: Install collabora
  ansible.builtin.apt:
    name:
      - coolwsd
      - code-brand
      - python3-lxml
      - collaboraoffice-dict*
      - collaboraofficebasis-*

- name: Create group cool
  ansible.builtin.group:
    name: cool
    system: true
    state: present

- name: Create user cool
  ansible.builtin.user:
    name: cool
    group: cool
    home: /opt/cool
    shell: /usr/sbin/nologin
    system: true
    state: present

- name: Create /etc/coolwsd
  ansible.builtin.file:
    path: /etc/coolwsd
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: "Allow nextcloud domain (1)"
  community.general.xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/storage/wopi/alias_groups
    pretty_print: true
    attribute: mode
    value: "groups"
  notify: Restart coolwsd

- name: "Allow nextcloud domain (2)"
  community.general.xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/storage/wopi/alias_groups
    pretty_print: true
    input_type: xml
    set_children: "<group><host allow='true'>https://{{ nextcloud_fqdn | regex_replace('\\.', '\\.') }}:443</host></group>"
  notify: Restart coolwsd

- name: "Setup allowed_languages"
  community.general.xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/allowed_languages
    value: "{{ collabora_allowed_languages }}"
  notify: Restart coolwsd

- name: "Disable Collabora SSL, since we have reverse proxy"
  community.general.xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/ssl/enable
    value: "false"
  notify: Restart coolwsd

- name: "Tell Collabora we use SSL reverse proxy"
  community.general.xml:
    path: /etc/coolwsd/coolwsd.xml
    xpath: /config/ssl/termination
    value: "true"
  notify: Restart coolwsd

- name: Start coolwsd
  ansible.builtin.systemd:
    name: coolwsd.service
    state: started
    enabled: true

- name: Wait until collabora is started
  ansible.builtin.wait_for:
    host: localhost
    port: 9980

- name: Setup apache
  ansible.builtin.include_tasks: apache.yml
  when: "'aptiko.general.apache' in ansible_role_names"

- name: Setup nginx
  ansible.builtin.include_tasks: nginx.yml
  when: "'aptiko.general.nginx' in ansible_role_names"
