#!/bin/bash

recordings_dir=$1

cd $recordings_dir
meeting_url=`jq -r '.meeting_url' metadata.json`
meeting_id=${meeting_url##*/}
mkdir -p /var/www/jibri/recordings/$meeting_id
mv *.mp4  /var/www/jibri/recordings/$meeting_id/
