---

dependencies:

  - role: aptiko.general.docker  # For AppAPI

  - role: aptiko.general.website
    website_domain: "{{ nextcloud_fqdn }}"
    website_document_root: "/var/www/{{ nextcloud_fqdn }}/nextcloud"
    website_ssl: "{{ nextcloud_ssl }}"

galaxy_info:
  author: Antonis Christofides
  description: Ansible role for installing nextcloud on Debian/Ubuntu
  license: GPLv3
  min_ansible_version: "2.19"
