---
- name: Gather jvb and jibri facts
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups[jitsi_jvb_group] | union(groups[jitsi_jibri_group] | default([])) }}"

- name: Install apt packages required for Jitsi
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk-headless
      - lua5.1
      - prosody
      - prosody-modules
      - git
      - maven
      - nodejs
      - make
      - unzip
    autoremove: true

- name: Import certificates tasks
  ansible.builtin.import_tasks: create_certificates.yml
- name: Import meet tasks
  ansible.builtin.import_tasks: meet.yml
- name: Import prosody tasks
  ansible.builtin.import_tasks: prosody.yml
- name: Import jicofo tasks
  ansible.builtin.import_tasks: jicofo.yml
- name: Import statistics tasks
  ansible.builtin.import_tasks: statistics.yml
  tags:
    - jitsi_statistics
  when: prometheus_server_ips|default([]) | length > 0
