---

- name: Restart Jicofo
  ansible.builtin.service:
    name: jitsi-jicofo
    state: restarted
    daemon-reload: true

- name: Restart prosody
  ansible.builtin.service:
    name: prosody
    state: restarted

- name: Compile Jitsi CSS
  ansible.builtin.command: make deploy-css
  args:
    chdir: /opt/jitsi-meet
  changed_when: true

- name: Restart jitsi-prometheus-exporter
  ansible.builtin.service:
    name: jitsi-prometheus-exporter
    state: restarted
    daemon-reload: true
