[nextcloud]
user = www-data
group = www-data
listen = /var/run/php{{ php_version }}-fpm-nextcloud.sock
listen.owner = www-data
listen.group = www-data
php_admin_value[disable_functions] = exec,passthru,shell_exec,system
php_admin_flag[allow_url_fopen] = off
pm = {{ nextcloud_fpm_mode }}
pm.max_children = {{ nextcloud_fpm_max_children }}
pm.start_servers = {{ nextcloud_fpm_start_servers }}
pm.min_spare_servers = {{ nextcloud_fpm_min_spare_servers }}
pm.max_spare_servers = {{ nextcloud_fpm_max_spare_servers }}
pm.process_idle_timeout = {{ nextcloud_fpm_process_idle_timeout }}
