---
dependencies:

 - role: aptiko.general.website
   website_domain: "{{ jitsi_fqdn }}"
   website_ssl: letsencrypt
   website_document_root: /opt/jitsi-meet

 - role: aptiko.general.node
   node_version: 20

 - role: grnet.jitsi.jitsi_excalidraw_backend
