---

dependencies:

  - role: aptiko.general.website
    website_domain: "{{ collabora_fqdn }}"
    website_document_root: "/var/www/{{ collabora_fqdn }}/nextcloud"
    website_ssl: letsencrypt


galaxy_info:
  author: Antonis Christofides
  description: Install Collabora for Nextcloud on Debian/Ubuntu
  license: GPLv3
  min_ansible_version: "2.19"
