---

- name: Install apt packages required for coturn
  ansible.builtin.apt:
    name:
      - coturn
      - ssl-cert
      - certbot

- name: Check if letsencrypt certificate exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ coturn_fqdn }}
  register: letsencryptdir

- name: Allow firewall for various STUN and TURN ports
  ansible.builtin.lineinfile:
    path: /etc/nftables/ansible-late.nft
    line: >-
      meta l4proto { tcp, udp }
      th dport { 80, 443, 3478, 3479, 5349, 5350 } accept
  notify: Reload nftables
  when:
    - base_setup_firewall | default(false)
    - coturn_setup_firewall

- name: Ensure nftables allows certbot
  ansible.builtin.meta: flush_handlers

- name: If we need to run certbot, ensure coturn is stopped
  ansible.builtin.service:
    name: coturn
    state: stopped
  when:
    - coturn_setup_letsencrypt
    - not letsencryptdir.stat.exists
  notify: Restart coturn

- name: Install letsencrypt certificate
  ansible.builtin.command: >-
    certbot certonly --standalone --non-interactive --agree-tos
    -m {{ coturn_letsencrypt_admin | mandatory }} -d {{ coturn_fqdn }}
  changed_when: true
  when:
    - coturn_setup_letsencrypt
    - not letsencryptdir.stat.exists

- name: Install turnserver.conf
  ansible.builtin.template:
    src: turnserver.conf
    dest: /etc/turnserver.conf
    mode: "0644"
  notify: Restart coturn

- name: Ensure systemd coturn drop-in directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/coturn.service.d
    state: directory
    mode: "0755"

- name: Install systemd coturn drop-in configuration file
  ansible.builtin.template:
    src: coturn-systemd.conf
    dest: /etc/systemd/system/coturn.service.d/coturn.conf
    mode: "0644"
  notify: Restart coturn

- name: Ensure letsencrypt renewal hook directories exist
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: "0755"
  loop:
    - pre
    - post
  when: coturn_setup_letsencrypt

- name: Stop coturn before letsencrypt renewal
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/pre/stop-coturn.sh
    mode: "0755"
    content: |
      #!/bin/sh
      systemctl stop coturn
  when: coturn_setup_letsencrypt

- name: Start coturn after letsencrypt renewal
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/post/start-coturn.sh
    mode: "0755"
    content: |
      #!/bin/sh
      systemctl start coturn
  when: coturn_setup_letsencrypt

- name: Remove obsolete letsencrypt deploy hook
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/deploy/restart-coturn.sh
    state: absent
  when: coturn_setup_letsencrypt
